version: '2.3'

services:
  kyoto-web:
    restart: always
    image: $dockerImageName
    labels:
      - "CO2"
      - "$dockerImageTag"
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nat

